### ISSUE TITLE
eval trigger

### ISSUE THREAD

**Issue by zakrush** [ajinabraham/njsscan#55]
Hello. 
Thank you for njsscan/
 I had fast test it and SonarQube with JuiceShop. I see that SonarQube have a simple regexp for eval function. And JSscan didn't  trigger for  this: https://github.com/bkimminich/juice-shop/blob/e07059edd3b4ed0527add13d0dd5c8570daa3bcc/routes/userProfile.js#L28

But SonarQube have a trigger. I was supprized with it easy case. Do you can add trigger on eval function into custom rules?

I use opensecurity/nodejsscan image

**Comment by zakrush** [comment]
semgrep security-audit found this issue:

```
userProfile.js
severity:warning rule:javascript.lang.security.detect-eval-with-expression.detect-eval-with-expression: Detected eval(variable), which could allow a malicious actor to run arbitrary code.

28:              username = eval(code) // eslint-disable-line no-eval

```

Can you import this rule to njsscan? How can I do it myself?

Will it work if I copy semgrep rule to src/rules/semantic_grep/exec of my docker image?

**Comment by ajinabraham** [comment]
We don't want to detect all occurrences of `eval()` as it will cause a lot of noise. Our rules try to detect if user input from an HTTP request param/body reaches `eval()`. 

https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/eval/eval_node.yaml#L16-L42

You could add your custom rule, but should include metadata that is required by njsscan.
```
   message: >-
      User controlled data in eval() or similar functions may result in Server
      Side Injection or Remote Code Injection
    languages:
      - javascript
    severity: ERROR
    metadata:
      owasp: 'A1: Injection'
      cwe: >-
        CWE-95: Improper Neutralization of Directives in Dynamically Evaluated
        Code ('Eval Injection')
```
The Juiceshop example is a second-order injection where the user input is coming from a database entry `user`. We just cannot determine if it's user input or not with semgrep. So it's a limitation I would say.
