### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by aravindvnair99** [ajinabraham/njsscan#61]
My workflow file is:

```yaml
name: njsscan sarif

on:
  push:
  schedule:
    - cron: '17 12 * * 0'

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@main
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@main
      with:
        sarif_file: results.sarif
```

Was working fine until the last run across multiple repositories which resulted in:

```console
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/github/codeql-action/main/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.sendStatusReport (/home/runner/work/_actions/github/codeql-action/main/lib/actions-util.js:506:9)
    at async run (/home/runner/work/_actions/github/codeql-action/main/lib/upload-sarif-action.js:25:11)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/main/lib/upload-sarif-action.js:46:9) {
  name: 'HttpError',
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 16 May 2021 12:56:40 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0402:578A:915A9:530DFB:60A11688',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4994',
    'x-ratelimit-reset': '1621173282',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '6',
    'x-xss-protection': '0'
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/owner/repo/code-scanning/analysis/status',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'CodeQL Action octokit-core.js/3.1.2 Node.js/12.13.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"workflow_run_id":847010182,"workflow_name":"njsscan sarif","job_name":"njsscan","analysis_key":".github/workflows/njsscan-analysis.yml:njsscan","commit_oid":"476da36d0e01e54675c410670f363d9bcce1d374","ref":"refs/heads/main","action_name":"upload-sarif","action_ref":"main","action_oid":"unknown","started_at":"2021-05-16T12:56:40.284Z","action_started_at":"2021-05-16T12:56:40.284Z","status":"starting","matrix_vars":"null"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest'
}
Error: Resource not accessible by integration
```
